### ISSUE TITLE
Facebook messenger issue when sign in

### ISSUE THREAD

**Issue by BtrJay** [MicrosoftDX/AuthBot#4]
Hi,

When I tested my bots on facebook  messenger, it displays the full login url in 3 different messages.

Skype does render it in sign-in button so it looks fine there.

Are there any ways to get this issue fixed?

Regards,

Jay

**Comment by duckwaffle** [comment]
Hi, the workaround solution that Jay and I came up with is to pull out the AzureAuthDialog from the source, and extend the login method to support SigninCard when the channel id equals "facebook", like so:

`if (msg.ChannelId == "skype")
                        {
                            IMessageActivity response = context.MakeMessage();
                            response.Recipient = msg.From;
                            response.Type = "message";

```
                        response.Attachments = new List<Attachment>();
                        List<CardAction> cardButtons = new List<CardAction>();
                        CardAction plButton = new CardAction()
                        {
                            Value = authenticationUrl,
                            Type = "signin",
                            Title = "Authentication Required"
                        };

                        cardButtons.Add(plButton);
                        SigninCard plCard = new SigninCard(this.prompt, new List<CardAction>() { plButton });
                        Attachment plAttachment = plCard.ToAttachment();
                        response.Attachments.Add(plAttachment);
                        await context.PostAsync(response);
                    }
                    else if (msg.ChannelId == "facebook")
                    {
                        var response = context.MakeMessage();
                        response.Recipient = msg.From;
                        response.Type = "message";

                        response.Text = prompt;
                        response.Attachments = new List<Attachment>();
                        response.Attachments.Add(SigninCard.Create("You need to authorize me",
                                                                   "Click Here!",
                                                                   authenticationUrl).ToAttachment());
                        await context.PostAsync(response);

                    }
                    else
                    {
                        await context.PostAsync(this.prompt + "[Click here](" + authenticationUrl + ")");
                    }`
```

A better solution would probably to change the "LogIn" method on the azureauthdialog to be protected virtual so that people can fully customise the login process with more than just the prompt text. Or even better, extract all the code in LogIn after the creation of the auth url/resumption cookie into a new overridable method that just handles text output based on the channel id.

Cheers,
Richard

**Comment by matvelloso** [comment]
FYI just made that method protected virtual as requested.
