### ISSUE TITLE
Link that redirects user to Azure AD login page fails

### ISSUE THREAD

**Issue by thelakkatmadhav** [MicrosoftDX/AuthBot#5]
The AD page that user redirects to says <We received a bad request - The request body must contain the following parameter: 'client_id'>. This happens in the new Bot emulator released a couple of days back and also in  the iFrame WebChat Channel. It continues to work on Skype and also in the old bot emulator.

**Comment by dqvy** [comment]
Same issue with Skype for iOS and the web ui from bot framework. I guess the issue is coming from the encoding of the URL. All get parameters including "&" are html encoded such as "&amp;". So Microsoft is not able to get all required parameters.

**Comment by palludavy** [comment]
Same issue with Skype for iOS and the web ui from bot framework. I guess the issue is coming from the encoding of the URL. All get parameters including "&" are html encoded such as "&amp;" for web ui or "252F&" for Skype for iOS. So Microsoft is not able to get all required parameters.

**Comment by eanders-ms** [comment]
Hi @thelakkatmadhav, A fix for this issue has been made in the new WebChat control: https://github.com/Microsoft/BotFramework-WebChat/pull/180. We plan to make a new emulator release this coming Thursday (12/1). In addition, we will hotpatch the Bot Framework's WebChat channel so that IFRAME'd clients will pick up the fix.
